# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
      - 'src/**'
    branches:
      - master
  pull_request:
    paths:
      - 'src/**'
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # 设置 node.js 环境
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      # 获取 yarn 的 cache 文件路径
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      # 设置包缓存目录，避免每次下载
      - name: Cache node modules
        id: yarn-cache 
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      # 安装依赖
      - name: Install dependences
        run: |
          npm install yarn -g,
          yarn
      - name: Build blog
        run: yarn docs:build
      # 发布
      - name: Deploy blog dist
        env:
          BLOG_DEPLOY_TOKEN: ${{ secrets.BLOG_DEPLOY_TOKEN }}
        run: yarn docs:deploy
